version: '3.4'

networks:
  myappnetwork:
    name: myappnetwork

services:
  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    ports:  
      - '7157:443'
    links:
      - sqldata
    depends_on:
      sqldata:
        condition: service_started
    networks:
      - myappnetwork

  doorapi:
    image: ${DOCKER_REGISTRY-}doorapi
    build:
      context: .
      dockerfile: DoorApi/Dockerfile
    ports:  
      - "7053:443"
    links:
      - sqldata
    depends_on:
      sqldata:
        condition: service_started
    networks:
      - myappnetwork

  adminapi:
    image: ${DOCKER_REGISTRY-}adminapi
    build:
      context: .
      dockerfile: AdminApi/Dockerfile
    ports:  
      - "7251:443"
    links:
      - sqldata
    depends_on:
      sqldata:
        condition: service_started
    networks:
      - myappnetwork

  inouthistoryapi:
    image: ${DOCKER_REGISTRY-}inouthistoryapi
    build:
      context: .
      dockerfile: InOutHistoryApi/Dockerfile
    ports:  
      - '7052:443'
    links:
      - historydata
    depends_on:
      historydata:
        condition: service_started
    networks:
      - myappnetwork

  dbmigration:
    image: ${DOCKER_REGISTRY-}dbmigration
    build:
      context: .
      dockerfile: DbMigration/Dockerfile
    links:
      - sqldata
    depends_on:
      sqldata:
        condition: service_started
    networks:
      - myappnetwork

  sqldata:  
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "MyPass@word"  
    volumes:  
      - ./data/mssql:/var/opt/mssql3
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:  
      - '1441:1433'
    networks:
      - myappnetwork

  historydata:  
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "MyPass@word"  
    volumes:  
      - ./data/mssql:/var/opt/mssql3
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:  
      - '1442:1433'
    networks:
      - myappnetwork

  


  

  

